issue-845-fix: true
with-expecter: true
resolve-type-alias: false
dir: "{{ .InterfaceDir }}/mocks"
outpkg: "mocks"
filename: "mock_{{ .InterfaceName | snakecase | lower }}.go"
mockname: "Mock{{ .InterfaceName }}"
inpackage: true
all: true
packages:
  github.com/agglayer/aggkit/agglayer:
  github.com/agglayer/aggkit/aggoracle/chaingersender:
  github.com/agglayer/aggkit/aggsender/db:
  github.com/agglayer/aggkit/aggsender/rpc:
  github.com/agglayer/aggkit/aggsender/types:
  github.com/agglayer/aggkit/bridgesync:
  github.com/agglayer/aggkit/l1infotreesync:
  github.com/agglayer/aggkit/reorgdetector:
  github.com/agglayer/aggkit/rpc/client:
  github.com/agglayer/aggkit/rpc:
  github.com/agglayer/aggkit/sync: