// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockBlockNotifier is an autogenerated mock type for the BlockNotifier type
type MockBlockNotifier struct {
	mock.Mock
}

type MockBlockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockNotifier) EXPECT() *MockBlockNotifier_Expecter {
	return &MockBlockNotifier_Expecter{mock: &_m.Mock}
}

// String provides a mock function with no fields
func (_m *MockBlockNotifier) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBlockNotifier_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockBlockNotifier_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockBlockNotifier_Expecter) String() *MockBlockNotifier_String_Call {
	return &MockBlockNotifier_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockBlockNotifier_String_Call) Run(run func()) *MockBlockNotifier_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockNotifier_String_Call) Return(_a0 string) *MockBlockNotifier_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockNotifier_String_Call) RunAndReturn(run func() string) *MockBlockNotifier_String_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: id
func (_m *MockBlockNotifier) Subscribe(id string) <-chan EventNewBlock {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan EventNewBlock
	if rf, ok := ret.Get(0).(func(string) <-chan EventNewBlock); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan EventNewBlock)
		}
	}

	return r0
}

// MockBlockNotifier_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBlockNotifier_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - id string
func (_e *MockBlockNotifier_Expecter) Subscribe(id interface{}) *MockBlockNotifier_Subscribe_Call {
	return &MockBlockNotifier_Subscribe_Call{Call: _e.mock.On("Subscribe", id)}
}

func (_c *MockBlockNotifier_Subscribe_Call) Run(run func(id string)) *MockBlockNotifier_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBlockNotifier_Subscribe_Call) Return(_a0 <-chan EventNewBlock) *MockBlockNotifier_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockNotifier_Subscribe_Call) RunAndReturn(run func(string) <-chan EventNewBlock) *MockBlockNotifier_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlockNotifier creates a new instance of MockBlockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockNotifier {
	mock := &MockBlockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
