// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// MockAgglayerClientInterface is an autogenerated mock type for the AgglayerClientInterface type
type MockAgglayerClientInterface struct {
	mock.Mock
}

type MockAgglayerClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgglayerClientInterface) EXPECT() *MockAgglayerClientInterface_Expecter {
	return &MockAgglayerClientInterface_Expecter{mock: &_m.Mock}
}

// GetCertificateHeader provides a mock function with given fields: certificateHash
func (_m *MockAgglayerClientInterface) GetCertificateHeader(certificateHash common.Hash) (*CertificateHeader, error) {
	ret := _m.Called(certificateHash)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateHeader")
	}

	var r0 *CertificateHeader
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Hash) (*CertificateHeader, error)); ok {
		return rf(certificateHash)
	}
	if rf, ok := ret.Get(0).(func(common.Hash) *CertificateHeader); ok {
		r0 = rf(certificateHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CertificateHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Hash) error); ok {
		r1 = rf(certificateHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgglayerClientInterface_GetCertificateHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateHeader'
type MockAgglayerClientInterface_GetCertificateHeader_Call struct {
	*mock.Call
}

// GetCertificateHeader is a helper method to define mock.On call
//   - certificateHash common.Hash
func (_e *MockAgglayerClientInterface_Expecter) GetCertificateHeader(certificateHash interface{}) *MockAgglayerClientInterface_GetCertificateHeader_Call {
	return &MockAgglayerClientInterface_GetCertificateHeader_Call{Call: _e.mock.On("GetCertificateHeader", certificateHash)}
}

func (_c *MockAgglayerClientInterface_GetCertificateHeader_Call) Run(run func(certificateHash common.Hash)) *MockAgglayerClientInterface_GetCertificateHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Hash))
	})
	return _c
}

func (_c *MockAgglayerClientInterface_GetCertificateHeader_Call) Return(_a0 *CertificateHeader, _a1 error) *MockAgglayerClientInterface_GetCertificateHeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgglayerClientInterface_GetCertificateHeader_Call) RunAndReturn(run func(common.Hash) (*CertificateHeader, error)) *MockAgglayerClientInterface_GetCertificateHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetEpochConfiguration provides a mock function with no fields
func (_m *MockAgglayerClientInterface) GetEpochConfiguration() (*ClockConfiguration, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEpochConfiguration")
	}

	var r0 *ClockConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func() (*ClockConfiguration, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *ClockConfiguration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ClockConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgglayerClientInterface_GetEpochConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEpochConfiguration'
type MockAgglayerClientInterface_GetEpochConfiguration_Call struct {
	*mock.Call
}

// GetEpochConfiguration is a helper method to define mock.On call
func (_e *MockAgglayerClientInterface_Expecter) GetEpochConfiguration() *MockAgglayerClientInterface_GetEpochConfiguration_Call {
	return &MockAgglayerClientInterface_GetEpochConfiguration_Call{Call: _e.mock.On("GetEpochConfiguration")}
}

func (_c *MockAgglayerClientInterface_GetEpochConfiguration_Call) Run(run func()) *MockAgglayerClientInterface_GetEpochConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgglayerClientInterface_GetEpochConfiguration_Call) Return(_a0 *ClockConfiguration, _a1 error) *MockAgglayerClientInterface_GetEpochConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgglayerClientInterface_GetEpochConfiguration_Call) RunAndReturn(run func() (*ClockConfiguration, error)) *MockAgglayerClientInterface_GetEpochConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestKnownCertificateHeader provides a mock function with given fields: networkID
func (_m *MockAgglayerClientInterface) GetLatestKnownCertificateHeader(networkID uint32) (*CertificateHeader, error) {
	ret := _m.Called(networkID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestKnownCertificateHeader")
	}

	var r0 *CertificateHeader
	var r1 error
	if rf, ok := ret.Get(0).(func(uint32) (*CertificateHeader, error)); ok {
		return rf(networkID)
	}
	if rf, ok := ret.Get(0).(func(uint32) *CertificateHeader); ok {
		r0 = rf(networkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CertificateHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(networkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestKnownCertificateHeader'
type MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call struct {
	*mock.Call
}

// GetLatestKnownCertificateHeader is a helper method to define mock.On call
//   - networkID uint32
func (_e *MockAgglayerClientInterface_Expecter) GetLatestKnownCertificateHeader(networkID interface{}) *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call {
	return &MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call{Call: _e.mock.On("GetLatestKnownCertificateHeader", networkID)}
}

func (_c *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call) Run(run func(networkID uint32)) *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint32))
	})
	return _c
}

func (_c *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call) Return(_a0 *CertificateHeader, _a1 error) *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call) RunAndReturn(run func(uint32) (*CertificateHeader, error)) *MockAgglayerClientInterface_GetLatestKnownCertificateHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendCertificate provides a mock function with given fields: certificate
func (_m *MockAgglayerClientInterface) SendCertificate(certificate *SignedCertificate) (common.Hash, error) {
	ret := _m.Called(certificate)

	if len(ret) == 0 {
		panic("no return value specified for SendCertificate")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(*SignedCertificate) (common.Hash, error)); ok {
		return rf(certificate)
	}
	if rf, ok := ret.Get(0).(func(*SignedCertificate) common.Hash); ok {
		r0 = rf(certificate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(*SignedCertificate) error); ok {
		r1 = rf(certificate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgglayerClientInterface_SendCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCertificate'
type MockAgglayerClientInterface_SendCertificate_Call struct {
	*mock.Call
}

// SendCertificate is a helper method to define mock.On call
//   - certificate *SignedCertificate
func (_e *MockAgglayerClientInterface_Expecter) SendCertificate(certificate interface{}) *MockAgglayerClientInterface_SendCertificate_Call {
	return &MockAgglayerClientInterface_SendCertificate_Call{Call: _e.mock.On("SendCertificate", certificate)}
}

func (_c *MockAgglayerClientInterface_SendCertificate_Call) Run(run func(certificate *SignedCertificate)) *MockAgglayerClientInterface_SendCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*SignedCertificate))
	})
	return _c
}

func (_c *MockAgglayerClientInterface_SendCertificate_Call) Return(_a0 common.Hash, _a1 error) *MockAgglayerClientInterface_SendCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgglayerClientInterface_SendCertificate_Call) RunAndReturn(run func(*SignedCertificate) (common.Hash, error)) *MockAgglayerClientInterface_SendCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// SendTx provides a mock function with given fields: signedTx
func (_m *MockAgglayerClientInterface) SendTx(signedTx SignedTx) (common.Hash, error) {
	ret := _m.Called(signedTx)

	if len(ret) == 0 {
		panic("no return value specified for SendTx")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(SignedTx) (common.Hash, error)); ok {
		return rf(signedTx)
	}
	if rf, ok := ret.Get(0).(func(SignedTx) common.Hash); ok {
		r0 = rf(signedTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(SignedTx) error); ok {
		r1 = rf(signedTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgglayerClientInterface_SendTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTx'
type MockAgglayerClientInterface_SendTx_Call struct {
	*mock.Call
}

// SendTx is a helper method to define mock.On call
//   - signedTx SignedTx
func (_e *MockAgglayerClientInterface_Expecter) SendTx(signedTx interface{}) *MockAgglayerClientInterface_SendTx_Call {
	return &MockAgglayerClientInterface_SendTx_Call{Call: _e.mock.On("SendTx", signedTx)}
}

func (_c *MockAgglayerClientInterface_SendTx_Call) Run(run func(signedTx SignedTx)) *MockAgglayerClientInterface_SendTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SignedTx))
	})
	return _c
}

func (_c *MockAgglayerClientInterface_SendTx_Call) Return(_a0 common.Hash, _a1 error) *MockAgglayerClientInterface_SendTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgglayerClientInterface_SendTx_Call) RunAndReturn(run func(SignedTx) (common.Hash, error)) *MockAgglayerClientInterface_SendTx_Call {
	_c.Call.Return(run)
	return _c
}

// WaitTxToBeMined provides a mock function with given fields: hash, ctx
func (_m *MockAgglayerClientInterface) WaitTxToBeMined(hash common.Hash, ctx context.Context) error {
	ret := _m.Called(hash, ctx)

	if len(ret) == 0 {
		panic("no return value specified for WaitTxToBeMined")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.Hash, context.Context) error); ok {
		r0 = rf(hash, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgglayerClientInterface_WaitTxToBeMined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitTxToBeMined'
type MockAgglayerClientInterface_WaitTxToBeMined_Call struct {
	*mock.Call
}

// WaitTxToBeMined is a helper method to define mock.On call
//   - hash common.Hash
//   - ctx context.Context
func (_e *MockAgglayerClientInterface_Expecter) WaitTxToBeMined(hash interface{}, ctx interface{}) *MockAgglayerClientInterface_WaitTxToBeMined_Call {
	return &MockAgglayerClientInterface_WaitTxToBeMined_Call{Call: _e.mock.On("WaitTxToBeMined", hash, ctx)}
}

func (_c *MockAgglayerClientInterface_WaitTxToBeMined_Call) Run(run func(hash common.Hash, ctx context.Context)) *MockAgglayerClientInterface_WaitTxToBeMined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Hash), args[1].(context.Context))
	})
	return _c
}

func (_c *MockAgglayerClientInterface_WaitTxToBeMined_Call) Return(_a0 error) *MockAgglayerClientInterface_WaitTxToBeMined_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgglayerClientInterface_WaitTxToBeMined_Call) RunAndReturn(run func(common.Hash, context.Context) error) *MockAgglayerClientInterface_WaitTxToBeMined_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgglayerClientInterface creates a new instance of MockAgglayerClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgglayerClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgglayerClientInterface {
	mock := &MockAgglayerClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
