// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAggLayerClientGetEpochConfiguration is an autogenerated mock type for the AggLayerClientGetEpochConfiguration type
type MockAggLayerClientGetEpochConfiguration struct {
	mock.Mock
}

type MockAggLayerClientGetEpochConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggLayerClientGetEpochConfiguration) EXPECT() *MockAggLayerClientGetEpochConfiguration_Expecter {
	return &MockAggLayerClientGetEpochConfiguration_Expecter{mock: &_m.Mock}
}

// GetEpochConfiguration provides a mock function with no fields
func (_m *MockAggLayerClientGetEpochConfiguration) GetEpochConfiguration() (*ClockConfiguration, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEpochConfiguration")
	}

	var r0 *ClockConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func() (*ClockConfiguration, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *ClockConfiguration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ClockConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEpochConfiguration'
type MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call struct {
	*mock.Call
}

// GetEpochConfiguration is a helper method to define mock.On call
func (_e *MockAggLayerClientGetEpochConfiguration_Expecter) GetEpochConfiguration() *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call {
	return &MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call{Call: _e.mock.On("GetEpochConfiguration")}
}

func (_c *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call) Run(run func()) *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call) Return(_a0 *ClockConfiguration, _a1 error) *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call) RunAndReturn(run func() (*ClockConfiguration, error)) *MockAggLayerClientGetEpochConfiguration_GetEpochConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAggLayerClientGetEpochConfiguration creates a new instance of MockAggLayerClientGetEpochConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggLayerClientGetEpochConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggLayerClientGetEpochConfiguration {
	mock := &MockAggLayerClientGetEpochConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
