// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockClientFactoryInterface is an autogenerated mock type for the ClientFactoryInterface type
type MockClientFactoryInterface struct {
	mock.Mock
}

type MockClientFactoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientFactoryInterface) EXPECT() *MockClientFactoryInterface_Expecter {
	return &MockClientFactoryInterface_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function with given fields: url
func (_m *MockClientFactoryInterface) NewClient(url string) ClientInterface {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 ClientInterface
	if rf, ok := ret.Get(0).(func(string) ClientInterface); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientInterface)
		}
	}

	return r0
}

// MockClientFactoryInterface_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockClientFactoryInterface_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - url string
func (_e *MockClientFactoryInterface_Expecter) NewClient(url interface{}) *MockClientFactoryInterface_NewClient_Call {
	return &MockClientFactoryInterface_NewClient_Call{Call: _e.mock.On("NewClient", url)}
}

func (_c *MockClientFactoryInterface_NewClient_Call) Run(run func(url string)) *MockClientFactoryInterface_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientFactoryInterface_NewClient_Call) Return(_a0 ClientInterface) *MockClientFactoryInterface_NewClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientFactoryInterface_NewClient_Call) RunAndReturn(run func(string) ClientInterface) *MockClientFactoryInterface_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientFactoryInterface creates a new instance of MockClientFactoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientFactoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientFactoryInterface {
	mock := &MockClientFactoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
