// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	types "github.com/agglayer/aggkit/aggsender/types"
	mock "github.com/stretchr/testify/mock"
)

// MockAggsenderInterface is an autogenerated mock type for the AggsenderInterface type
type MockAggsenderInterface struct {
	mock.Mock
}

type MockAggsenderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggsenderInterface) EXPECT() *MockAggsenderInterface_Expecter {
	return &MockAggsenderInterface_Expecter{mock: &_m.Mock}
}

// Info provides a mock function with no fields
func (_m *MockAggsenderInterface) Info() types.AggsenderInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 types.AggsenderInfo
	if rf, ok := ret.Get(0).(func() types.AggsenderInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.AggsenderInfo)
	}

	return r0
}

// MockAggsenderInterface_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockAggsenderInterface_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockAggsenderInterface_Expecter) Info() *MockAggsenderInterface_Info_Call {
	return &MockAggsenderInterface_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockAggsenderInterface_Info_Call) Run(run func()) *MockAggsenderInterface_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggsenderInterface_Info_Call) Return(_a0 types.AggsenderInfo) *MockAggsenderInterface_Info_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggsenderInterface_Info_Call) RunAndReturn(run func() types.AggsenderInfo) *MockAggsenderInterface_Info_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAggsenderInterface creates a new instance of MockAggsenderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggsenderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggsenderInterface {
	mock := &MockAggsenderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
